#### What we will use
1. IAM roles and users
2. S3 buckets
3. Complete Infrastracture of AWS Sagemaker - Training, Endpoints

In [18]:
import os

os.environ["OS_OPT"] = "linux"

import sagemaker
from sagemaker.core.helper.session_helper import Session
from sklearn.model_selection import train_test_split
import boto3
import pandas as pd
from dotenv import load_dotenv

load_dotenv()
role = os.getenv("SAGEMAKER_ROLE_ARN")

sm_boto3 = boto3.client("sagemaker")
sess = Session()
region = sess.boto_session.region_name
bucket = "mobbucketsagemaker123321"
print("Using bucket" + bucket)

Using bucketmobbucketsagemaker123321

In [19]:
print(region)

eu-west-3

In [20]:
df = pd.read_csv("mob_price_classification_train.csv")
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

df.shape

In [21]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [22]:
df['price_range'].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [23]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [24]:
features = list(df.columns)
features

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

In [25]:
label = features.pop(-1)
label

'price_range'

In [26]:
x=df[features]
y=df[label]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.15,random_state=0)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1700, 20)
(300, 20)
(1700,)
(300,)

In [29]:
trainX = pd.DataFrame(X_train)
trainX[label] = y_train

testX=pd.DataFrame(X_test)
testX[label] = y_test

In [30]:
trainX

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
1452,1450,0,2.1,0,1,0,31,0.6,114,5,...,1573,1639,794,11,5,9,0,1,1,1
1044,1218,1,2.8,1,3,0,39,0.8,150,7,...,1122,1746,1667,10,0,12,0,0,0,1
1279,1602,0,0.6,0,12,0,58,0.4,170,1,...,1259,1746,3622,17,2,17,0,1,1,3
674,1034,0,2.6,1,2,1,45,0.3,190,3,...,182,1293,969,15,1,7,1,0,0,0
1200,530,0,2.4,0,1,0,32,0.3,88,6,...,48,1012,959,17,7,6,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,1224,1,1.6,0,9,0,33,1.0,157,1,...,522,563,3796,10,5,13,1,1,0,3
1216,1158,0,0.7,1,1,1,29,0.7,123,2,...,311,1796,1542,17,9,15,1,0,1,1
1653,1190,0,2.0,1,0,0,40,0.2,93,5,...,1399,1646,3610,13,7,9,0,0,1,3
559,1191,0,2.4,1,2,0,13,0.9,169,1,...,179,1813,1028,14,6,8,1,1,1,0
684,706,0,0.5,0,13,1,31,0.1,108,3,...,543,938,2419,8,7,4,1,0,1,1

In [31]:
trainX.to_csv("train-V-1.csv", index=False)
testX.to_csv("test-V-1.csv", index=False)

In [32]:
bucket

'mobbucketsagemaker123321'

In [33]:
## send data to S3. Sagemkaer will take the data for training from s3
sk_prefix="sagemaker/mobile_price_classification/sklearncontainer"
trainpath=sess.upload_data(path='train-V-1.csv', bucket=bucket, key_prefix = sk_prefix)
testpath=sess.upload_data(path='test-V-1.csv', bucket=bucket, key_prefix = sk_prefix)
print(trainpath)
print(testpath)

s3://mobbucketsagemaker123321/sagemaker/mobile_price_classification/sklearncontainer/train-V-1.csv
s3://mobbucketsagemaker123321/sagemaker/mobile_price_classification/sklearncontainer/test-V-1.csv

## Script used by AWS Sagemaker to train models

In [34]:
%%writefile src/script.py

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score
import sklearn
import joblib
import boto3
import pathlib
from io import StringIO
import argparse
import os
import numpy as np
import pandas as pd

def model_fn(model_dir):
    clf = joblib.load(os.path.join(model_dir, "model.joblib"))
    return clf


if __name__=="__main__":
    print("[Info] Extracting arguments")
    parser = argparse.ArgumentParser()

    # Hyperparameter
    parser.add_argument("--n-estimators", type=int, default=100)
    parser.add_argument("--random-state", type=int, default=0)

    ### Data, model and output directories
    parser.add_argument("--model-dir", type=str, default=os.environ.get("SM_MODEL_DIR"))
    parser.add_argument("--train", type=str, default=os.environ.get("SM_CHANNEL_TRAIN"))
    parser.add_argument("--test", type=str, default=os.environ.get("SM_CHANNEL_TEST"))
    parser.add_argument("--train-file", type=str, default="train-V-1.csv")
    parser.add_argument("--test-file", type=str, default="test-V-1.csv")

    args, _ = parser.parse_known_args()

    print("SKLearn Version: ", sklearn.__version__)
    print("Jobliv Version: ", joblib.__version__)

    print("[INFO] Reading data")
    print()
    train_df = pd.read_csv(os.path.join(args.train, args.train_file))
    test_df = pd.read_csv(os.path.join(args.test, args.test_file))

    features = list(train_df.columns)
    label = features.pop(-1)

    print("Building training and testing datasets")
    print()
    X_train = train_df[features]
    X_test = test_df[features]
    y_train = train_df[label]
    y_test = test_df[label]

    print('Column order: ')
    print(features)
    print()

    print("Label column is: ", label)
    print()

    print("Data shape: ")
    print()
    print("Shape of training data (85%):")
    print(X_train.shape)
    print(y_train.shape)
    print()
    print("Shape of testing data (15%):")
    print(X_test.shape)
    print(y_test.shape)
    print()

    print("Training RandomForest Model...")
    print()
    model=RandomForestClassifier(n_estimators=args.n_estimators, random_state=args.random_state,\
                                 verbose=2, n_jobs=1)

    model.fit(X_train,y_train)

    print()

    model_path = os.path.join(args.model_dir, "model.joblib")
    joblib.dump(model, model_path)

    print("Model saved at " + model_path)

    y_pred_test = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_rep = classification_report(y_test, y_pred_test)

    print()
    print("Metrics on test")
    print("Total rows are: ", X_test.shape[0])
    print('[TESTING] Model accuracy is: ', test_acc)
    print('[TESTING] Testing report: ')
    print(test_rep)

Overwriting src/script.py

### AWS Sagemaker Entry point to Execute the Training script

In [36]:
from sagemaker.core import image_uris
from sagemaker.core.helper.session_helper import Session
from sagemaker.train import ModelTrainer
from sagemaker.train.configs import (
    Compute,
    SourceCode,
    StoppingCondition,
)



# 1. Retrieve the Scikit-learn ECR image URI using sess
sess = Session()
image_uri = image_uris.retrieve(
    framework="sklearn",
    region=sess.boto_region_name,
    version="1.2-1",
    py_version="py3",
    instance_type="ml.m5.large"
)

# 2. Configure Compute hardware & enable spot training
compute_config = Compute(
    instance_type="ml.m5.large",
    instance_count=1,
    enable_managed_spot_training=True,
)

# 3. Configure StoppingCondition timeouts
stopping_config = StoppingCondition(
    max_runtime_in_seconds=3600,     # Max training time: 1 hour
    max_wait_time_in_seconds=7200,    # Max total spot wait time: 2 hours
)


# 4. Configure Source Code (source_dir is required when entry_script is provided)
source_config = SourceCode(
    source_dir="src",                   # Current directory where script.py lives
    entry_script="script.py"
)

# 5. Instantiate ModelTrainer
sklearn_trainer = ModelTrainer(
    training_image=image_uri,
    role=role,
    source_code=source_config,
    compute=compute_config,
    stopping_condition=stopping_config,
    base_job_name="RF-custom-sklearn",
    hyperparameters={
        "n_estimators": "100",
        "random_state": "0",
    },
)

# To launch training in v3:
# from sagemaker.train.configs import InputData
# train_data = InputData(channel_name="train", data_source="s3://your-bucket/train.csv")
# sklearn_trainer.train(input_data_config=[train_data])

[07/31/26 16:44:57] INFO     SageMaker session not provided. Using default Session.                  ]8;id=12399300;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=12399301;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/defaults.py#65\65]8;;\

[07/31/26 16:44:58] INFO     Role 'arn:aws:iam::414069442977:role/sagemakeraccess'         ]8;id=12399308;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/helper/iam_role_resolver.py\iam_role_resolver.py]8;;\:]8;id=12399309;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/helper/iam_role_resolver.py#598\598]8;;\
                             validated for training. Using it.

[07/31/26 16:45:00] INFO     OutputDataConfig not provided. Using default:                          ]8;id=12399315;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/defaults.py\defaults.py]8;;\:]8;id=12399316;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/defaults.py#192\192]8;;\
                             s3_output_path='s3://sagemaker-eu-west-3-414069442977/RF-custom-sklear
                             n' kms_key_id=None compression_type='GZIP'

                    INFO     Training image URI:                                               ]8;id=12399323;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/model_trainer.py\model_trainer.py]8;;\:]8;id=12399324;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/train/model_trainer.py#558\558]8;;\
                             659782779980.dkr.ecr.eu-west-3.amazonaws.com/sagemaker-scikit-lea
                             rn:1.2-1-cpu-py3

In [37]:
from sagemaker.train.configs import Compute, StoppingCondition

print("Compute fields:", list(Compute.model_fields.keys()))
print("StoppingCondition fields:", list(StoppingCondition.model_fields.keys()))

Compute fields: ['instance_type', 'instance_count', 'volume_size_in_gb', 'volume_kms_key_id', 'keep_alive_period_in_seconds', 'instance_groups', 'training_plan_arn', 'instance_placement_config', 'enable_managed_spot_training']
StoppingCondition fields: ['max_runtime_in_seconds', 'max_wait_time_in_seconds', 'max_pending_time_in_seconds']

In [39]:
# launch training
from sagemaker.train.configs import InputData
inputs = [
    InputData(channel_name="train", data_source=trainpath),
    InputData(channel_name="test", data_source=testpath),
]
sklearn_trainer.train(input_data_config=inputs)

[07/31/26 16:45:14] INFO     SageMaker Python SDK will collect telemetry to help us better ]8;id=12399331;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/telemetry/telemetry_logging.py\telemetry_logging.py]8;;\:]8;id=12399332;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/telemetry/telemetry_logging.py#304\304]8;;\
                             understand our user's needs, diagnose issues, and deliver
                             additional features.
                             To opt out of telemetry, please disable via TelemetryOptOut
                             parameter in SDK defaults config. For more information, refer
                             to
                             https://sagemaker.readthedocs.io/en/stable/overview.html#conf
                             iguring-and-using-defaults-with-the-sagemaker-python-sdk.

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/tiziana/.config/sagemaker/config.yaml

[07/31/26 16:45:19] INFO     Creating training_job resource.                                     ]8;id=12399339;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399340;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31239\31239]8;;\

                    WARNING  No region provided. Using default region.                                 ]8;id=12399347;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/utils/utils.py\utils.py]8;;\:]8;id=12399348;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/utils/utils.py#361\361]8;;\

[07/31/26 16:45:20] INFO     Found credentials in shared credentials file: ~/.aws/credentials   ]8;id=12399353;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/botocore/credentials.py\credentials.py]8;;\:]8;id=12399354;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/botocore/credentials.py#1392\1392]8;;\

/home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

[07/31/26 16:47:47] INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399360;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399361;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Starting training script

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399366;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399367;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ /miniconda3/bin/python3 --version

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399372;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399373;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Python 3.9.21

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399378;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399379;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             /opt/ml/input/config/resourceconfig.json:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399384;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399385;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo /opt/ml/input/config/resourceconfig.json:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399390;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399391;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ cat /opt/ml/input/config/resourceconfig.json

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399396;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399397;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             {"current_host":"algo-1","current_instance_type":"ml.m5.large","cur
                             rent_group_name":"homogeneousCluster","hosts":["algo-1"],"instance_
                             groups":[{"instance_group_name":"homogeneousCluster","instance_type
                             ":"ml.m5.large","hosts":["algo-1"]}],"network_interface_name":"eth0
                             ","topology":null}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399402;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399403;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             /opt/ml/input/config/inputdataconfig.json:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399408;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399409;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399414;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399415;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo /opt/ml/input/config/inputdataconfig.json:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399420;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399421;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ cat /opt/ml/input/config/inputdataconfig.json

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399426;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399427;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             {"code":{"TrainingInputMode":"File","S3DistributionType":"FullyRepl
                             icated","RecordWrapperType":"None"},"sm_drivers":{"TrainingInputMod
                             e":"File","S3DistributionType":"FullyReplicated","RecordWrapperType
                             ":"None"},"test":{"TrainingInputMode":"File","S3DistributionType":"
                             FullyReplicated","RecordWrapperType":"None"},"train":{"TrainingInpu
                             tMode":"File","S3DistributionType":"FullyReplicated","RecordWrapper
                             Type":"None"}}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399432;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399433;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399438;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399439;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo 'Setting up environment variables'

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399444;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399445;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ /miniconda3/bin/python3
                             /opt/ml/input/data/sm_drivers/scripts/environment.py

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399450;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399451;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Setting up environment variables

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399456;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399457;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             No GPUs detected (normal if no gpus installed)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399462;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399463;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             No Neurons detected (normal if no neurons installed)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399468;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399469;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Environment Variables:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399474;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399475;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             NVIDIA_VISIBLE_DEVICES=void

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399480;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399481;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SKLEARN_MMS_CONFIG=/home/model-server/config.properties

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399486;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399487;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PYTHONUNBUFFERED=1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399492;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399493;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=******

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399498;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399499;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SAGEMAKER_TRAINING_MODULE=sagemaker_sklearn_container.training:main

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399504;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399505;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             HOSTNAME=ip-10-0-206-117.eu-west-3.compute.internal

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399510;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399511;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_TRAINING_CONFIG_FILE=/opt/ml/input/config/hyperparameters.
                             json

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399516;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399517;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             AWS_REGION=eu-west-3

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399522;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399523;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PWD=/

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399528;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399529;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SAGEMAKER_MANAGED_WARMPOOL_CACHE_DIRECTORY=/opt/ml/sagemaker/warmpo
                             olcache

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399534;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399535;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             HOME=/root

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399540;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399541;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             LANG=C.UTF-8

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399546;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399547;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             DMLC_INTERFACE=eth0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399552;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399553;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT=/opt/ml/input

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399558;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399559;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PYTHONIOENCODING=UTF-8

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399564;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399565;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             TEMP=/home/model-server/tmp

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399570;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399571;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SHLVL=1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399576;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399577;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SAGEMAKER_SKLEARN_VERSION=1.2-1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399582;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399583;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PYTHONDONTWRITEBYTECODE=1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399588;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399589;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PIP_ROOT_USER_ACTION=ignore

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399594;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399595;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             TRAINING_JOB_NAME=RF-custom-sklearn-20260731164514

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399600;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399601;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             LC_ALL=C.UTF-8

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399606;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399607;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             TRAINING_JOB_ARN=arn:aws:sagemaker:eu-west-3:414069442977:training-
                             job/RF-custom-sklearn-20260731164514

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399612;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399613;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             PATH=/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
                             bin:/sbin:/bin

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399618;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399619;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_DATA_CONFIG_FILE=/opt/ml/input/config/inputdataconfig.json

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399624;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399625;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SAGEMAKER_SERVING_MODULE=sagemaker_sklearn_container.serving:main

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399630;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399631;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             DEBIAN_FRONTEND=noninteractive

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399636;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399637;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHECKPOINT_CONFIG_FILE=/opt/ml/input/config/checkpointconfig.jso
                             n

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399642;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399643;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_MODEL_DIR=/opt/ml/model

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399648;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399649;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             _=/miniconda3/bin/python3

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399654;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399655;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_MODEL_DIR=/opt/ml/model

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399660;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399661;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_DIR=/opt/ml/input

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399666;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399667;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_DATA_DIR=/opt/ml/input/data

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399672;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399673;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_CONFIG_DIR=/opt/ml/input/config

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399678;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399679;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_OUTPUT_DIR=/opt/ml/output

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399684;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399685;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_OUTPUT_FAILURE=/opt/ml/output/failure

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399690;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399691;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_OUTPUT_DATA_DIR=/opt/ml/output/data

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399696;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399697;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_LOG_LEVEL=20

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399702;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399703;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_MASTER_ADDR=algo-1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399708;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399709;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_MASTER_PORT=7777

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399714;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399715;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_SOURCE_DIR=/opt/ml/input/data/code

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399720;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399721;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_ENTRY_SCRIPT=script.py

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399726;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399727;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHANNEL_CODE=/opt/ml/input/data/code

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399732;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399733;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHANNEL_SM_DRIVERS=/opt/ml/input/data/sm_drivers

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399738;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399739;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHANNEL_TEST=/opt/ml/input/data/test

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399744;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399745;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHANNEL_TRAIN=/opt/ml/input/data/train

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399750;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399751;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CHANNELS=['code', 'sm_drivers', 'test', 'train']

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399756;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399757;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_HP_N_ESTIMATORS=100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399762;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399763;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_HP_RANDOM_STATE=0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399768;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399769;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_HPS={"n_estimators": 100, "random_state": 0}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399774;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399775;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CURRENT_HOST=algo-1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399780;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399781;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CURRENT_INSTANCE_TYPE=ml.m5.large

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399786;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399787;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_HOSTS=['algo-1']

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399792;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399793;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_NETWORK_INTERFACE_NAME=eth0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399798;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399799;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_HOST_COUNT=1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399804;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399805;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_CURRENT_HOST_RANK=0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399810;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399811;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_NUM_CPUS=2

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399816;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399817;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_NUM_GPUS=0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399822;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399823;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_NUM_NEURONS=0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399828;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399829;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_RESOURCE_CONFIG={"current_host": "algo-1",
                             "current_instance_type": "ml.m5.large", "current_group_name":
                             "homogeneousCluster", "hosts": ["algo-1"], "instance_groups":
                             [{"instance_group_name": "homogeneousCluster", "instance_type":
                             "ml.m5.large", "hosts": ["algo-1"]}], "network_interface_name":
                             "eth0", "topology": null}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399834;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399835;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_INPUT_DATA_CONFIG={"code": {"TrainingInputMode": "File",
                             "S3DistributionType": "FullyReplicated", "RecordWrapperType":
                             "None"}, "sm_drivers": {"TrainingInputMode": "File",
                             "S3DistributionType": "FullyReplicated", "RecordWrapperType":
                             "None"}, "test": {"TrainingInputMode": "File",
                             "S3DistributionType": "FullyReplicated", "RecordWrapperType":
                             "None"}, "train": {"TrainingInputMode": "File",
                             "S3DistributionType": "FullyReplicated", "RecordWrapperType":
                             "None"}}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399840;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399841;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SM_TRAINING_ENV={"channel_input_dirs": {"code":
                             "/opt/ml/input/data/code", "sm_drivers":
                             "/opt/ml/input/data/sm_drivers", "test": "/opt/ml/input/data/test",
                             "train": "/opt/ml/input/data/train"}, "current_host": "algo-1",
                             "current_instance_type": "ml.m5.large", "hosts": ["algo-1"],
                             "master_addr": "algo-1", "master_port": 7777, "hyperparameters":
                             {"n_estimators": 100, "random_state": 0}, "input_data_config":
                             {"code": {"TrainingInputMode": "File", "S3DistributionType":
                             "FullyReplicated", "RecordWrapperType": "None"}, "sm_drivers":
                             {"TrainingInputMode": "File", "S3DistributionType":
                             "FullyReplicated", "RecordWrapperType": "None"}, "test":
                             {"TrainingInputMode": "File", "S3DistributionType":
                             "FullyReplicated", "RecordWrapperType": "None"}, "train":
                             {"TrainingInputMode": "File", "S3DistributionType":
                             "FullyReplicated", "RecordWrapperType": "None"}},
                             "input_config_dir": "/opt/ml/input/config", "input_data_dir":
                             "/opt/ml/input/data", "input_dir": "/opt/ml/input", "job_name":
                             "RF-custom-sklearn-20260731164514", "log_level": 20, "model_dir":
                             "/opt/ml/model", "network_interface_name": "eth0", "num_cpus": 2,
                             "num_gpus": 0, "num_neurons": 0, "output_data_dir":
                             "/opt/ml/output/data", "resource_config": {"current_host":
                             "algo-1", "current_instance_type": "ml.m5.large",
                             "current_group_name": "homogeneousCluster", "hosts": ["algo-1"],
                             "instance_groups": [{"instance_group_name": "homogeneousCluster",
                             "instance_type": "ml.m5.large", "hosts": ["algo-1"]}],
                             "network_interface_name": "eth0", "topology": null}}

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399846;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399847;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ set +x

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399852;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399853;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ cd /opt/ml/input/data/code

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399858;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399859;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Running Basic Script driver

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399864;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399865;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo 'Running Basic Script driver'

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399870;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399871;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ /miniconda3/bin/python3
                             /opt/ml/input/data/sm_drivers/distributed_drivers/basic_script_driv
                             er.py

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399876;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399877;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Executing command: /miniconda3/bin/python3 script.py --n_estimators
                             100 --random_state 0

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399882;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399883;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [Info] Extracting arguments

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399888;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399889;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             SKLearn Version:  1.2.1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399894;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399895;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Jobliv Version:  1.5.1

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399900;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399901;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [INFO] Reading data

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399906;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399907;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Building training and testing datasets

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399912;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399913;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Column order:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399918;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399919;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
                             'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
                             'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time',
                             'three_g', 'touch_screen', 'wifi']

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399924;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399925;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Label column is:  price_range

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399930;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399931;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Data shape:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399936;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399937;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Shape of training data (85%):

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399942;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399943;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             (1700, 20)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399948;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399949;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             (1700,)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399954;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399955;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Shape of testing data (15%):

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399960;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399961;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             (300, 20)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399966;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399967;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             (300,)

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399972;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399973;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Training RandomForest Model...

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399978;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399979;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 1 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399984;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399985;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 2 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399990;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399991;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 3 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12399996;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12399997;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 4 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400002;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400003;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 5 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400008;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400009;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 6 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400014;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400015;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 7 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400020;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400021;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 8 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400026;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400027;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 9 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400032;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400033;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 10 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400038;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400039;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 11 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400044;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400045;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 12 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400050;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400051;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 13 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400056;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400057;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 14 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400062;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400063;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 15 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400068;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400069;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 16 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400074;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400075;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 17 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400080;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400081;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 18 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400086;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400087;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 19 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400092;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400093;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 20 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400098;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400099;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 21 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400104;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400105;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 22 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400110;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400111;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 23 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400116;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400117;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 24 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400122;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400123;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 25 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400128;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400129;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 26 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400134;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400135;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 27 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400140;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400141;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 28 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400146;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400147;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 29 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400152;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400153;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 30 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400158;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400159;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 31 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400164;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400165;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 32 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400170;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400171;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 33 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400176;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400177;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 34 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400182;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400183;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 35 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400188;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400189;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 36 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400194;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400195;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 37 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400200;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400201;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 38 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400206;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400207;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 39 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400212;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400213;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 40 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400218;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400219;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.1s

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400224;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400225;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 41 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400230;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400231;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 42 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400236;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400237;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 43 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400242;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400243;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 44 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400248;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400249;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 45 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400254;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400255;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 46 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400260;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400261;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 47 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400266;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400267;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 48 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400272;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400273;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 49 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400278;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400279;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 50 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400284;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400285;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 51 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400290;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400291;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 52 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400296;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400297;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 53 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400302;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400303;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 54 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400308;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400309;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 55 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400314;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400315;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 56 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400320;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400321;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 57 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400326;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400327;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 58 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400332;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400333;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 59 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400338;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400339;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 60 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400344;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400345;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 61 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400350;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400351;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 62 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400356;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400357;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 63 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400362;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400363;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 64 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400368;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400369;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 65 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400374;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400375;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 66 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400380;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400381;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 67 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400386;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400387;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 68 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400392;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400393;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 69 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400398;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400399;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 70 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400404;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400405;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 71 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400410;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400411;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 72 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400416;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400417;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 73 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400422;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400423;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 74 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400428;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400429;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 75 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400434;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400435;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 76 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400440;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400441;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 77 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400446;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400447;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 78 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400452;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400453;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 79 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400458;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400459;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 80 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400464;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400465;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 81 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400470;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400471;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 82 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400476;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400477;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 83 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400482;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400483;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 84 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400488;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400489;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 85 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400494;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400495;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 86 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400500;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400501;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 87 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400506;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400507;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 88 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400512;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400513;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 89 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400518;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400519;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 90 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400524;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400525;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 91 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400530;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400531;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 92 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400536;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400537;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 93 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400542;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400543;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 94 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400548;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400549;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 95 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400554;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400555;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 96 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400560;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400561;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 97 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400566;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400567;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 98 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400572;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400573;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 99 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400578;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400579;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             building tree 100 of 100

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400584;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400585;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.3s
                             finished

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400590;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400591;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Model saved at /opt/ml/model/model.joblib

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400596;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400597;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.0s

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400602;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400603;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s
                             finished

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400608;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400609;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Metrics on test

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400614;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400615;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Total rows are:  300

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400620;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400621;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [TESTING] Model accuracy is:  0.8833333333333333

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400626;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400627;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             [TESTING] Testing report:

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400632;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400633;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             precision    recall  f1-score   support

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400638;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400639;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             0       0.95      1.00      0.97        69

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400644;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400645;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             1       0.85      0.80      0.83        66

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400650;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400651;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             2       0.80      0.77      0.79        74

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400656;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400657;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             3       0.91      0.95      0.93        91

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400662;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400663;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             accuracy                           0.88       300

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400668;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400669;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             macro avg       0.88      0.88      0.88       300

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400674;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400675;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             weighted avg       0.88      0.88      0.88       300

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400680;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400681;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             ++ echo 'Training Container Execution Completed'

                    INFO     RF-custom-sklearn-20260731164514/algo-1-1785509098:                 ]8;id=12400686;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400687;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31585\31585]8;;\
                             Training Container Execution Completed

[07/31/26 16:47:58] INFO     Final Resource Status: Completed                                    ]8;id=12400693;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400694;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31591\31591]8;;\

In [40]:
import boto3

# Get the exact training job name from SageMaker v3 TrainingJob object
job_name = sklearn_trainer._latest_training_job.training_job_name
print(f"Fetching CloudWatch logs for Training Job: {job_name}\n")

# Initialize CloudWatch Logs client
logs_client = boto3.client("logs")
log_group = "/aws/sagemaker/TrainingJobs"

try:
    # Fetch log streams for this job
    streams_response = logs_client.describe_log_streams(
        logGroupName=log_group, logStreamNamePrefix=job_name
    )
    streams = streams_response.get("logStreams", [])

    if not streams:
        print("No log streams found for this job yet.")
    else:
        # Loop through streams and output log messages
        for stream in streams:
            events_response = logs_client.get_log_events(
                logGroupName=log_group,
                logStreamName=stream["logStreamName"],
                limit=100,
            )
            for event in events_response.get("events", []):
                print(event["message"].strip())

except Exception as e:
    print(f"Error fetching CloudWatch logs: {e}")

Fetching CloudWatch logs for Training Job: RF-custom-sklearn-20260731164514

building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.1s
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.3s finished
Model saved at /opt/ml/model/model.joblib
[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished
Metrics on test
Total rows are:  300
[TESTING] Model accuracy is:  0.8833333333333333
[TESTING] Testing report:
precision    recall  f1-score   support
0       0.95      1.00      0.97        69
1       0.85      0.80      0.83        66
2       0.80      0.77      0.79        74
3       0.91      0.95      0.93        91
accuracy                           0.88       300
macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300
++ echo 'Training Container Execution Completed'
Training Container Execution Completed

##  To get the model from S3

In [ ]:
sklearn_trainer._latest_training_job.wait(logs=False)

artifact = sm_boto3.describe_training_job(
    TrainingJobName=sklearn_trainer._latest_training_job.training_job_name
)["ModelArtifacts"]["S3ModelArtifacts"]

[07/31/26 16:52:00] INFO     Final Resource Status: Completed                                    ]8;id=12400699;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py\resources.py]8;;\:]8;id=12400700;file:///home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/sagemaker/core/resources.py#31591\31591]8;;\

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:4                                                                                    │
│                                                                                                  │
│   1 sklearn_trainer._latest_training_job.wait(logs=False)                                        │
│   2                                                                                              │
│   3 artifact = sm_boto3.describe_training_job(                                                   │
│ ❱ 4 │   TrainingJobName=sklearn_trainer._latest_training_job.job_name                            │
│   5 )["ModelArtifacts"]["S3ModelArtifacts"]                                                      │
│   6                                                                                              │
│                                                                                                  │
│ /home/tiziana/miniconda3/envs/awssagemaker/lib/python3.10/site-packages/pydantic/main.py:1042 in │
│ __getattr__                                                                                      │
│                                                                                                  │
│   1039 │   │   │   │   │   │   return super().__getattribute__(item)  # Raises AttributeError i  │
│   1040 │   │   │   │   │   else:                                                                 │
│   1041 │   │   │   │   │   │   # this is the current error                                       │
│ ❱ 1042 │   │   │   │   │   │   raise AttributeError(f'{type(self).__name__!r} object has no att  │
│   1043 │   │                                                                                     │
│   1044 │   │   def __setattr__(self, name: str, value: Any) -> None:                             │
│   1045 │   │   │   if (setattr_handler := self.__pydantic_setattr_handlers__.get(name)) is not   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'TrainingJob' object has no attribute 'job_name'

In [ ]:
artifact